extends:
    - airbnb
rules:
    strict: off
    no-console: off
    no-unused-vars: off
    no-await-in-loop: off
    no-restricted-syntax: off
    no-promise-executor-return: off
ignorePatterns:
    - tests/integration-tests/configs/**
    - test/integration-tests/resources/**
env:
    mocha: true
