name: Test, Lint and Publish
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Publish Node package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x, 14.x, 16.x ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Install and test
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm run build
      - run: npm run lint
      - run: npm test

      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.2.1

      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ steps.extract_version.outputs.version }}',
              sha: context.sha
            })

      - name: Make changelog
        id: create_changelog
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          - toTag: 'v${{ steps.extract_version.outputs.version }}'

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 'v${{ steps.extract_version.outputs.version }}'
          body: ${{steps.create_changelog.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish new version
        # Note: Setting NODE_AUTH_TOKEN as job|workspace wide env var won't work
        #       as it appears actions/setup-node sets own value
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --verbose

      - name: Print dirs
        if: failure()
        run: find /home/runner/.npm/_logs/ -type f -exec cat {} \;